Repository DNXLabs/one-cli, pull requests merged in 2020-10, with the labels that each got.

#94 Shell command and --port option
  one/__init__.py
  one/commands/shell.py
  one/docker/container.py
  one/docker/image.py
  one/one.py
Labels: hacktoberfest, hacktoberfest-accepted

#96 Add option to send AWS params to auth iam
  one/commands/auth.py
Labels: CI/CD, auth, command, hacktoberfest, hacktoberfest-accepted

#98 Add Okta SSO to list of IDP providers from One CLI
  .gitignore
  one/commands/auth.py
  one/docker/image.py
  one/prompt/idp.py
  one/utils/environment/idp.py
Labels: feature, hacktoberfest, hacktoberfest-accepted
